#!/bin/bash

# Place this file in the 'boot' folder on the microSD card.

# This command creates a temporary systemd service that runs on boot.
# It first sets the hostname, waits for the network, then downloads and executes the main script.
systemd-run --unit=github-pull-startup --on-active=15 --timer-property=AccuracySec=1s /bin/bash -c 'hostnamectl set-hostname pi-mocap-1; while ! ping -c 1 -W 1 github.com; do sleep 1; done; curl -sSL https://raw.githubusercontent.com/kindakwiatek/PnP-ArUco-marker-tracking/main/start_tracking.sh | bash'
