#!/bin/bash

# Place this file in the 'boot' folder on the microSD card.

# This command creates a temporary systemd service that runs on boot.
# It waits for the network, then downloads and executes the main script from GitHub.
systemd-run --unit=github-pull --on-active=10 --timer-property=AccuracySec=1s /bin/bash -c 'while ! ping -c 1 -W 1 github.com; do sleep 1; done; curl -sSL https://raw.githubusercontent.com/kindakwiatek/PnP-ArUco-marker-tracking/main/start_tracking.sh | bash'
